# Generated by Django 4.2 on 2025-08-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("final_prediction", models.CharField(blank=True, max_length=10)),
                ("overall_confidence", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="foodimage",
            options={"ordering": ["view_type"]},
        ),
        migrations.RemoveField(
            model_name="foodimage",
            name="brand_text",
        ),
        migrations.AddField(
            model_name="foodimage",
            name="detected_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="foodimage",
            name="view_type",
            field=models.CharField(
                choices=[
                    ("front", "Front View"),
                    ("back", "Back View"),
                    ("side", "Side View"),
                    ("barcode", "Barcode/QR"),
                    ("other", "Other View"),
                ],
                default="front",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="foodimage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="detector.foodproduct",
            ),
        ),
    ]
